---
- name: Add Docker GPG key
  apt_key:
    url: "{{ GPG_docker_link }}"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable
    state: present

- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Create /etc/docker directory
  file:
    path: /etc/docker
    state: directory

- name: Copy daemon.json file
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: restarted
