apiVersion: v1
# Kind for volume chain
kind: PersistentVolume
metadata:
  name: auth-db-persistent-volume
  labels:
    type: local
    app: auth-db-persistent-volume
spec:
  storageClassName: auth
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/auth-db"