apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-persistent-volume
  labels:
    type: local
    app: rabbitmq-persistent-volume
spec:
  storageClassName: rabbitmq
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/data/rabbitmq"