FROM python:3.11-slim-bookworm

COPY ./ /backend
WORKDIR /backend
EXPOSE 8000
RUN pip install -r requirements.txt
CMD ["python", "-m", "uvicorn", "main:app", "--host", "$APP_HOST", "--port", "$APP_PORT", "--workers", "$APP_WORKERS"]