Vagrant.configure("2") do |config|

  config.vm.box = "debian/bullseye64"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "my_vm"
    vb.memory = "4096"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--vram", "128"]

  end
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.verbose = "v"
  end
end
