apiVersion: v1
kind: ConfigMap
metadata:
  name: alerter-configmap
data:
  DB_HOST: "{{ .Values.postgresql.primary.service.name }}"
  DB_PORT: "{{ .Values.postgresql.primary.service.port }}"

  RABBITMQ_HOST: "{{ .Values.rabbitmq.service.name }}"
  RABBITMQ_PORT: "{{ .Values.rabbitmq.service.port }}"
