apiVersion: v1
kind: ConfigMap
metadata:
  name: alerter-configmap
data:
  DB_HOST: {{ .Values.alerter_db.service.name }}
  DB_PORT: {{ .Values.alerter_db.service.port }}

  RABBITMQ_HOST: {{ .Values.rabbitmq.service.name }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.service.port }}
