apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  TIME_INTERVAL: {{ .Values.apps_settings.backend.time_interval }}
  AUTH_HOST: {{ .Values.apps_settings.auth.host }}
  AUTH_PORT: {{ .Values.apps_settings.auth.port }}
  CRYPTO_HOST: {{ .Values.apps_settings.crypto.host }}
  CRYPTO_PORT: {{ .Values.apps_settings.crypto.port }}

  DB_HOST: {{ .Values.databases.backend-db.service.name }}
  DB_PORT: {{ .Values.databases.backend-db.service.port }}

  REDIS_HOST: {{ .Values.redis-instances.backend-redis.service.name }}
  REDIS_PORT: {{ .Values.redis-instances.backend-redis.service.port }}

  RABBITMQ_HOST: {{ .Values.rabbitmq.service.name }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.service.port }}

  S3_HOST: {{ .Values.s3-data.host }}
  S3_PORT: {{ .Values.s3-data.port }}
  S3_BUCKET_NAME: {{ .Values.s3-data.bucket_name }}

  APP_HOST: "0.0.0.0"
  APP_PORT: {{ .Values.apps_settings.backend.port }}
