apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  TIME_INTERVAL: "10"
  AUTH_HOST: "web-store-auth"
  AUTH_PORT: "11000"
  CRYPTO_HOST: "web-store-crypto"
  CRYPTO_PORT: "5000"

  DB_HOST: "web-store-backend-db"
  DB_PORT: "5432"

  REDIS_HOST: "web-store-cache"
  REDIS_PORT: "6379"

  RABBITMQ_HOST: "web-store-rabbitmq"
  RABBITMQ_PORT: "5672"

  S3_HOST: "192.168.1.9"
  S3_PORT: "9000"
  S3_BUCKET_NAME: "items"

  APP_HOST: "0.0.0.0"
  APP_PORT: "8000"
