apiVersion: v1
# Kind for volume chain
kind: PersistentVolume
metadata:
  name: backend-db-persistent-volume
  labels:
    type: local
    app: backend-db-persistent-volume
spec:
  storageClassName: backend
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/backend-db"