apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: web_store_auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web_store_auth
  template:
    metadata:
      labels:
        app: web_store_auth
    spec:
      containers:
      - name: web_store_auth
        image: web_store_auth
        ports:
        - containerPort: 11000
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: auth_db_secrets
                key: DB_USER

          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: auth_db_secrets
                key: DB_PASS

          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: auth_configMap
                key:  DB_HOST

          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: auth_db_secrets
                key: DB_NAME

          - name: ACCESS_TOKEN_EXPIRE_MINUTES
            valueFrom:
              configMapKeyRef:
                name: auth_configMap
                key: ACCESS_TOKEN_EXPIRE_MINUTES

          - name: APP_HOST
            valueFrom:
              configMapKeyRef:
                name: auth_configMap
                key: APP_HOST

          - name: APP_PORT
            valueFrom:
              configMapKeyRef:
                name: auth_configMap
                key: APP_PORT

          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: auth_configMap
                key: REDIS_HOST

          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: auth_configMap
                key: REDIS_PORT
