apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: web-store-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-store-cache
  template:
    metadata:
      labels:
        app: web-store-cache
    spec:
      containers:
      - name: web-store-cache
        image: redis:7.4-rc2-alpine3.20
        ports:
        - containerPort: 6379