apiVersion: v1
kind: Secret
metadata:
  name: alerter_db-secrets
type: Opaque
data:
  DB_USER: "{{ .Values.alerter_db.auth.username | b64enc | quote }}"
  DB_PASS: "{{ .Values.alerter_db.auth.password | b64enc | quote }}"
  DB_NAME: "{{ .Values.alerter_db.auth.database | b64enc | quote }}"