apiVersion: v1
kind: Secret
metadata:
  name: alerter_db-secrets
type: Opaque
data:
  DB_USER: { { .Values.alerter_db.username | b64enc | quote } }
  DB_PASS: { { .Values.alerter_db.password | b64enc | quote } }
  DB_NAME: { { .Values.alerter_db.database | b64enc | quote } }