apiVersion: v1
kind: Secret
metadata:
  name: alerter-db-secrets
type: Opaque
data:
  DB_USER: { { .Values.alerter-db.username | b64enc | quote } }
  DB_PASS: { { .Values.alerter-db.password | b64enc | quote } }
  DB_NAME: { { .Values.alerter-db.database | b64enc | quote } }