apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secrets
type: Opaque
data:
  DB_USER: {{ .Values.databases.auth-db.username | b64enc | quote }}
  DB_PASS: {{ .Values.databases.auth-db.password | b64enc | quote }}
  DB_NAME: {{ .Values.databases.auth-db.database | b64enc | quote }}