apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  SECRET_KEY: {{ .Values.auth_secrets.secret_key | b64enc | quote }}
  ALGORITHM: {{ .Values.auth_secrets.algorithm | b64enc | quote }}