apiVersion: v1
kind: Secret
metadata:
  name: backend-db-secrets
type: Opaque
data:
  DB_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  DB_PASS: {{ .Values.postgresql.auth.password | b64enc | quote }}
  DB_NAME: {{ .Values.postgresql.auth.database | b64enc | quote }}
