apiVersion: v1
kind: Secret
metadata:
  name: backend-db-secrets
type: Opaque
data:
  DB_USER: {{ .Values.databases.backend-db.username | b64enc | quote }}
  DB_PASS: {{ .Values.databases.backend-db.password | b64enc | quote }}
  DB_NAME: {{ .Values.databases.backend-db.database | b64enc | quote }}
