apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: "{{ .Values.rabbitmq.auth.username | b64enc | quote }}"
  RABBITMQ_DEFAULT_PASS: "{{ .Values.rabbitmq.auth.password | b64enc | quote }}"
