apiVersion: v1
kind: Secret
metadata:
  name: s3-secrets
type: Opaque
data:
  ACCESS_KEY: {{ .Values.s3-data.access_key | b64enc | quote }}
  SECRET_KEY: {{ .Values.s3-data.secret_key | b64enc | quote }}
