---
- name: "Remove conflicting grafana packages"
  ansible.builtin.package:
    name: grafana-data
    state: absent

- name: "Install dependencies"
  ansible.builtin.package:
    name: "{{ _grafana_dependencies }}"
    state: present
    update_cache: true
  when: "(_grafana_dependencies | default())"


- name: Install necessary packages
  apt:
    name:
      - adduser
      - libfontconfig1
      - musl
    state: present
    update_cache: yes

- name: Download Grafana
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_11.1.3_amd64.deb
    dest: /tmp/grafana_11.1.3_amd64.deb

- name: Install Grafana package
  apt:
    deb: /tmp/grafana_11.1.3_amd64.deb

- name: "Install Grafana"
  ansible.builtin.package:
    name: "{{ grafana_package }}"
    state: "{{ (grafana_version == 'latest') | ternary('latest', 'present') }}"
  notify: restart_grafana
